import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import DeckGL from "@deck.gl/react";
import { useState, useEffect } from "react";
import { LineLayer, BitmapLayer, GeoJsonLayer } from "@deck.gl/layers";
import { _GlobeView as GlobeView } from "@deck.gl/core";
import { FlyToInterpolator } from "@deck.gl/core";

// import mapChapters.json from public/data/ folder
import chapterData from "../public/data/mapChapters.json";

export default function Home() {
  const [chapter, setChapter] = useState(0);

  const [viewState, setViewState] = useState({
    longitude: chapterData[0].longitude,
    latitude: chapterData[0].latitude,
    zoom: chapterData[0].zoom,
  });

  // create a function to add +1 to chapter on click
  const nextChapter = () => {
    setChapter(chapter + 1);
  };

  const previousChapter = () => {
    setChapter(chapter - 1);
  };

  // useEffect on chapter to update viewState
  useEffect(() => {
    setViewState({
      longitude: chapterData[chapter].longitude,
      latitude: chapterData[chapter].latitude,
      zoom: chapterData[chapter].zoom,
      transitionDuration: chapterData[chapter].duration,
      transitionInterpolator: new FlyToInterpolator(),
    });
  }, [chapter]);

  console.log(chapter);

  // Data to be used by the LineLayer
  const data = [
    {
      sourcePosition: [-122.41669, 37.7853],
      targetPosition: [-122.41669, 37.781],
    },
  ];

  const layers = [
    new BitmapLayer({
      id: "bitmap-layer",
      // add bitmap image from public/image/ folder
      image: "/img/worldMap.jpg",
      bounds: [
        [-180, -90, -35000],
        [-180, 90, -35000],
        [180, 90, -35000],
        [180, -90, -35000],
      ],
      // opacity: chapterData[counter].worldTile,
      // transitions: {
      //   opacity: {
      //     duration: 2500,
      //     enter: (value) => [value[0], value[1], value[2], 0], // fade in
      //   },
      // },
    }),

    new LineLayer({
      id: "line-layer",
      data,

      // Custom styling
      getStrokeWidth: 5,
      getColor: [255, 0, 0],
    }),
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>World Migration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DeckGL
          initialViewState={viewState}
          controller={true}
          layers={layers}
          views={new GlobeView()}
        />
        <nav id="navigation">
          <div>Previous</div>
          <div onClick={nextChapter}>Next</div>
        </nav>
      </main>
    </div>
  );
}
